@BaseUrl = https://localhost:7014

### Enroll a gym
POST {{BaseUrl}}/gyms/enroll
Content-Type: application/json

{
  "code": "lcub",
  "name": "LE CUBE"
}

### Set a bouldering route
POST {{BaseUrl}}/routes/set
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; filename="routePicture.jpg"; name=routePicture
Content-Type: image/jpeg

< ../Resource/routePicture.jpg
--boundary
Content-Disposition: form-data; name=payload
Content-Type: application/json

{
  "gymId": "0192d4f2-1019-7300-a89b-6d4aa19c1e73",
  "color": "yellow"
}
--boundary--
