@BaseUrl = https://localhost:7014

### Enroll a gym
POST {{BaseUrl}}/gyms/enroll
Content-Type: application/json

{
  "code": "lcub",
  "name": "LE CUBE"
}

### Set a bouldering route
POST {{BaseUrl}}/routes/set
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; filename="routePicture.jpg"; name=routePicture
Content-Type: image/jpeg

< ../Resources/routePicture.jpg
--boundary
Content-Disposition: form-data; filename="hold-a.png"; name="hold-a.png"
Content-Type: image/png

< ../Resources/yellowHold.png
--boundary
Content-Disposition: form-data; name=route
Content-Type: application/json

{
  "gymId": "0192da67-d9c5-79cc-b48a-1214ba506424",
  "color": "yellow",
  "holds": [
    {
      "segmentation": "hold-a.png",
      "x": 60,
      "y": 500
    }
  ]
}
--boundary--
